spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/skillsprint}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI:https://cognito-idp.${COGNITO_REGION:ap-southeast-1}.amazonaws.com/${COGNITO_USER_POOL_ID:ap-southeast-1_zyLksLSqU}}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
  cognito:
    region: ${COGNITO_REGION:ap-southeast-1}
    user-pool-id: ${COGNITO_USER_POOL_ID:ap-southeast-1_zyLksLSqU}
    client-id: ${COGNITO_CLIENT_ID}
    client-secret: ${COGNITO_CLIENT_SECRET:}
    default-group: ${COGNITO_DEFAULT_GROUP:LEARNER}
    access-key-id: ${AWS_ACCESS_KEY_ID:}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
  s3:
    region: ${AWS_REGION:ap-southeast-1}
    bucket: ${AWS_S3_BUCKET}
    public-base-url: ${AWS_S3_PUBLIC_BASE_URL}
    access-key-id: ${AWS_ACCESS_KEY_ID:}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
    upload-url-expiration-minutes: ${AWS_S3_UPLOAD_URL_EXPIRATION_MINUTES:10}
